### ISSUE TITLE
Setup failures are seen by client as connection closed 

### ISSUE THREAD

**Issue by yschimke** [rsocket/rsocket-java#311]
Client receives the error frame with a useful reason, but it doesn't bubble up to callers.

**Comment by yschimke** [comment]
Test that shows the problem

https://github.com/yschimke/rsocket-java/pull/1

**Comment by yschimke** [comment]
10:33:47,747 DEBUG [reactor-tcp-nio-7] (ClientServerInputMultiplexer.java) - receiving -> Frame => Stream ID: 0 Type: SETUP Version: 99.34 keep-alive interval: 30000 max lifetime: 90000 metadata mime type: application/binary data mime type: application/binary Payload: 
10:33:47,749  INFO [Time-limited test] (Loggers.java) - onSubscribe(FluxConcatArray.ConcatArraySubscriber)
10:33:47,753  INFO [Time-limited test] (Loggers.java) - request(unbounded)
10:33:47,755 DEBUG [reactor-tcp-nio-7] (ClientServerInputMultiplexer.java) - sending -> Frame => Stream ID: 0 Type: ERROR Error code: 1 Payload: data: "Unsupported version 99.34" 
10:33:47,760 DEBUG [reactor-tcp-nio-6] (ClientServerInputMultiplexer.java) - receiving -> Frame => Stream ID: 0 Type: ERROR Error code: 1 Payload: data: "Unsupported version 99.34" 
io.rsocket.exceptions.InvalidSetupException: Unsupported version 99.34
	at io.rsocket.exceptions.Exceptions.from(Exceptions.java:43)
	at io.rsocket.RSocketClient.handleStreamZero(RSocketClient.java:387)
	at io.rsocket.RSocketClient.handleIncomingFrames(RSocketClient.java:375)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:165)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:173)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:235)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:188)
	at reactor.core.publisher.FluxGroupBy$UnicastGroupedFlux.drainRegular(FluxGroupBy.java:566)
	at reactor.core.publisher.FluxGroupBy$UnicastGroupedFlux.drain(FluxGroupBy.java:642)
	at reactor.core.publisher.FluxGroupBy$UnicastGroupedFlux.subscribe(FluxGroupBy.java:707)
	at reactor.core.publisher.FluxPeekFuseable.subscribe(FluxPeekFuseable.java:86)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:183)
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replayNormal(FluxReplay.java:779)
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replay(FluxReplay.java:863)
	at reactor.core.publisher.ReplayProcessor.onNext(ReplayProcessor.java:523)
	at reactor.core.publisher.MonoProcessor.drainLoop(MonoProcessor.java:473)
	at reactor.core.publisher.MonoProcessor.onNext(MonoProcessor.java:321)
	at io.rsocket.internal.ClientServerInputMultiplexer.lambda$new$1(ClientServerInputMultiplexer.java:99)
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:132)
	at reactor.core.publisher.FluxGroupBy$GroupByMain.drainLoop(FluxGroupBy.java:396)
	at reactor.core.publisher.FluxGroupBy$GroupByMain.drain(FluxGroupBy.java:332)
	at reactor.core.publisher.FluxGroupBy$GroupByMain.onNext(FluxGroupBy.java:212)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:108)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:108)
	at reactor.ipc.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:207)
	at reactor.ipc.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:322)
	at reactor.ipc.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:316)
	at reactor.ipc.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:125)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)
10:33:47,772 DEBUG [Time-limited test] (ClientServerInputMultiplexer.java) - sending -> Frame => Stream ID: 1 Type: REQUEST_STREAM Initial Request N: 2147483647 Payload: metadata: "META" data: "REQUEST" 
10:33:47,773  WARN [reactor-tcp-nio-6] (Slf4JLogger.java) - An exception 'reactor.core.Exceptions$ErrorCallbackNotImplemented: java.io.IOException: Connection reset by peer' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)
10:33:47,784 ERROR [reactor-tcp-nio-6] (Loggers.java) - onError(java.nio.channels.ClosedChannelException)
10:33:47,784 ERROR [reactor-tcp-nio-6] (Loggers.java) - 
java.nio.channels.ClosedChannelException
	at io.rsocket.RSocketClient.<clinit>(RSocketClient.java:44)
	at io.rsocket.RSocketFactory$ClientRSocketFactory$StartClient.lambda$start$2(RSocketFactory.java:255)
	at reactor.core.publisher.MonoThenMap$ThenMapMain.onNext(MonoThenMap.java:120)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:126)
	at io.rsocket.transport.netty.client.TcpClientTransport.lambda$null$0(TcpClientTransport.java:66)
	at reactor.ipc.netty.channel.ChannelOperations.applyHandler(ChannelOperations.java:381)
	at reactor.ipc.netty.channel.ChannelOperations.onHandlerStart(ChannelOperations.java:301)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)
java.nio.channels.ClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)

reactor.core.Exceptions$ReactiveException: java.nio.channels.ClosedChannelException

	at reactor.core.Exceptions.propagate(Exceptions.java:219)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:85)
	at reactor.core.publisher.Mono.block(Mono.java:1301)
	at io.rsocket.integration.VersionMismatchTest.testBadVersion(VersionMismatchTest.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:86)
		... 14 more
Caused by: java.nio.channels.ClosedChannelException
	at io.rsocket.RSocketClient.<clinit>(RSocketClient.java:44)
	at io.rsocket.RSocketFactory$ClientRSocketFactory$StartClient.lambda$start$2(RSocketFactory.java:255)
	at reactor.core.publisher.MonoThenMap$ThenMapMain.onNext(MonoThenMap.java:120)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:126)
	at io.rsocket.transport.netty.client.TcpClientTransport.lambda$null$0(TcpClientTransport.java:66)
	at reactor.ipc.netty.channel.ChannelOperations.applyHandler(ChannelOperations.java:381)
	at reactor.ipc.netty.channel.ChannelOperations.onHandlerStart(ChannelOperations.java:301)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	... 1 more

**Comment by yschimke** [comment]
@robertroeser this shows the problem I was having in the setup version PR

**Comment by robertroeser** [comment]
Ok so on setup the error is propagated up the subscriber chain?

**Comment by yschimke** [comment]
@robertroeser this is an attempt at a fix https://github.com/rsocket/rsocket-java/pull/317/files

Needs a thorough review of both the test behaviour I expect, and the way I fixed it in RSocketClient.
