### ISSUE TITLE
Simple TCP server-client test does not work in 0.12.2-RC3 and up

### ISSUE THREAD

**Issue by piotr-signalfx** [rsocket/rsocket-java#675]
Hi,

Starting from 0.12.2-RC3 the following simple test case does not work:
```
    public static void main(String[] args) {
        CloseableChannel server = RSocketFactory.receive()
                .acceptor((setup, rSocket) -> Mono.just(new AbstractRSocket() {
                    @Override
                    public Mono<Payload> requestResponse(Payload payload) {
                        return Mono.just(DefaultPayload.create("PONG"));
                    }
                }))
                .transport(TcpServerTransport.create("localhost", 8001))
                .start()
                .block();

        RSocket client = RSocketFactory.connect()
                .transport(TcpClientTransport.create("localhost", 8001))
                .start()
                .block();
        Mono<Payload> pong = client.requestResponse(DefaultPayload.create("PING"));
        System.out.println(pong.block());
        server.onClose().block();
    }
```

The output I get looks as follows:
```
3:05:18.105 [reactor-tcp-nio-5] DEBUG reactor.netty.resources.PooledConnectionProvider - [id: 0x56c17189, L:/127.0.0.1:52958 - R:localhost/127.0.0.1:8001] Channel connected, now 1 active connections and 0 inactive connections
13:05:38.076 [parallel-1] DEBUG io.rsocket.FrameLogger - sending -> 
Frame => Stream ID: 0 Type: KEEPALIVE Flags: 0b10000000 Length: 14
Data:

13:05:58.075 [parallel-1] DEBUG io.rsocket.FrameLogger - sending -> 
Frame => Stream ID: 0 Type: KEEPALIVE Flags: 0b10000000 Length: 14
Data:

13:06:18.075 [parallel-1] DEBUG io.rsocket.FrameLogger - sending -> 
Frame => Stream ID: 0 Type: KEEPALIVE Flags: 0b10000000 Length: 14
Data:

13:06:38.074 [parallel-1] DEBUG io.rsocket.FrameLogger - sending -> 
Frame => Stream ID: 0 Type: KEEPALIVE Flags: 0b10000000 Length: 14
Data:

io.rsocket.exceptions.ConnectionErrorException: No keep-alive acks for 90000 ms
	at io.rsocket.RSocketClient.terminate(RSocketClient.java:114)
	at io.rsocket.keepalive.KeepAliveSupport.tryTimeout(KeepAliveSupport.java:110)
	at io.rsocket.keepalive.KeepAliveSupport$ClientKeepAliveSupport.onIntervalTick(KeepAliveSupport.java:146)
	at io.rsocket.keepalive.KeepAliveSupport.lambda$start$0(KeepAliveSupport.java:54)
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:130)
	at reactor.core.publisher.FluxInterval$IntervalRunnable.run(FluxInterval.java:123)
	at reactor.core.scheduler.PeriodicWorkerTask.call(PeriodicWorkerTask.java:59)
	at reactor.core.scheduler.PeriodicWorkerTask.run(PeriodicWorkerTask.java:73)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
13:06:58.081 [reactor-tcp-nio-5] DEBUG reactor.netty.resources.PooledConnectionProvider - [id: 0x56c17189, L:/127.0.0.1:52958 ! R:localhost/127.0.0.1:8001] Channel cleaned, now 0 active connections and 1 inactive connections
13:06:58.081 [reactor-tcp-nio-5] DEBUG reactor.netty.ReactorNetty - [id: 0x56c17189, L:/127.0.0.1:52958 ! R:localhost/127.0.0.1:8001] Non Removed handler: RSocketLengthCodec, context: ChannelHandlerContext(RSocketLengthCodec, [id: 0x56c17189, L:/127.0.0.1:52958 ! R:localhost/127.0.0.1:8001]), pipeline: DefaultChannelPipeline{(RSocketLengthCodec = io.rsocket.transport.netty.RSocketLengthCodec), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
13:06:58.083 [reactor-tcp-nio-6] DEBUG reactor.netty.ReactorNetty - [id: 0x4092d57c, L:/127.0.0.1:8001 ! R:/127.0.0.1:52958] Non Removed handler: RSocketLengthCodec, context: ChannelHandlerContext(RSocketLengthCodec, [id: 0x4092d57c, L:/127.0.0.1:8001 ! R:/127.0.0.1:52958]), pipeline: DefaultChannelPipeline{(RSocketLengthCodec = io.rsocket.transport.netty.RSocketLengthCodec), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
13:06:58.085 [parallel-1] DEBUG reactor.core.publisher.Operators - onNextDropped: CompositeByteBuf(ridx: 0, widx: 14, cap: 14, components=2)
13:06:58.086 [reactor-tcp-nio-5] DEBUG reactor.netty.resources.PooledConnectionProvider - [id: 0x56c17189, L:/127.0.0.1:52958 ! R:localhost/127.0.0.1:8001] onStateChange(ChannelOperations{PooledConnection{channel=[id: 0x56c17189, L:/127.0.0.1:52958 ! R:localhost/127.0.0.1:8001]}}, [disconnecting])
13:06:58.086 [reactor-tcp-nio-5] DEBUG reactor.netty.channel.ChannelOperationsHandler - [id: 0x56c17189, L:/127.0.0.1:52958 ! R:localhost/127.0.0.1:8001] Terminated ChannelOperation. Dropping Pending Write: 
13:06:58.087 [reactor-tcp-nio-5] DEBUG reactor.netty.channel.ChannelOperationsHandler - [id: 0x56c17189, L:/127.0.0.1:52958 ! R:localhost/127.0.0.1:8001] Terminated ChannelOperation. Dropping Pending Write: 
Exception in thread "main" reactor.netty.channel.AbortedException: Connection has been closed
	at reactor.netty.channel.ChannelOperationsHandler.discard(ChannelOperationsHandler.java:356)
	at reactor.netty.channel.ChannelOperationsHandler.drain(ChannelOperationsHandler.java:366)
	at reactor.netty.channel.ChannelOperationsHandler.handlerRemoved(ChannelOperationsHandler.java:210)
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerRemoved(AbstractChannelHandlerContext.java:997)
	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:638)
	at io.netty.channel.DefaultChannelPipeline.destroyDown(DefaultChannelPipeline.java:887)
	at io.netty.channel.DefaultChannelPipeline.destroyUp(DefaultChannelPipeline.java:853)
	at io.netty.channel.DefaultChannelPipeline.destroy(DefaultChannelPipeline.java:845)
	at io.netty.channel.DefaultChannelPipeline.access$700(DefaultChannelPipeline.java:46)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelUnregistered(DefaultChannelPipeline.java:1390)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:181)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:167)
	at io.netty.channel.DefaultChannelPipeline.fireChannelUnregistered(DefaultChannelPipeline.java:830)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:834)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:93)
		at reactor.core.publisher.Mono.block(Mono.java:1494)

```

**Comment by mostroverkhov** [comment]
Hello @piotr-signalfx ,

just ran example against `0.12.2-RC4` tag and head of `develop` w/o any issues.
In provided snippet `RSocket.requestResponse` stream is not subscribed to - 
```
 Mono<Payload> pong = client.requestResponse(DefaultPayload.create("PING"));
        System.out.println(pong);
```

so I modified It a bit

```
public static void main(String[] args) {
        CloseableChannel server =
                RSocketFactory.receive()
                        .acceptor(
                                (setup, rSocket) ->
                                        Mono.just(
                                                new AbstractRSocket() {
                                                    @Override
                                                    public Mono<Payload> requestResponse(Payload payload) {
                                                        return Mono.just(DefaultPayload.create("PONG"));
                                                    }
                                                }))
                        .transport(TcpServerTransport.create("localhost", 8001))
                        .start()
                        .block();

        RSocket client =
                RSocketFactory.connect()
                        .keepAlive(Duration.ofSeconds(1), Duration.ofSeconds(3),3)
                        .transport(TcpClientTransport.create("localhost", 8001))
                        .start()
                        .block();
        Mono<Payload> pong = client.requestResponse(DefaultPayload.create("PING"));
        Flux.interval(Duration.ofMillis(1))
                .onBackpressureDrop()
                .flatMap(v -> pong.map(Payload::getDataUtf8))
                .window(Duration.ofSeconds(1))
                .flatMap(Flux::count)
                .subscribe(
                        count -> System.out.println(String.format("%s - %d",Instant.now(),count)),
                        err -> System.out.println(err));

        client.onClose().block();
    }
```
and again had no issues with above code versions. 

If you are using `0.12.2-RC3`, I suggest to update to newer version, otherwise we need more info to reproduce this.

**Comment by piotr-signalfx** [comment]
Changing the code snippet I provided as follows:
``` System.out.println(pong.block());```
Issue is still reproducible

**Comment by piotr-signalfx** [comment]
With your version of the code:
```4:42:47.303 [reactor-tcp-nio-5] DEBUG reactor.netty.resources.PooledConnectionProvider - [id: 0x9a58b06f, L:/127.0.0.1:49439 - R:localhost/127.0.0.1:8001] Channel connected, now 1 active connections and 0 inactive connections
14:42:48.290 [parallel-1] DEBUG io.rsocket.FrameLogger - sending -> 
Frame => Stream ID: 0 Type: KEEPALIVE Flags: 0b10000000 Length: 14
Data:

14:42:49.288 [parallel-1] DEBUG io.rsocket.FrameLogger - sending -> 
Frame => Stream ID: 0 Type: KEEPALIVE Flags: 0b10000000 Length: 14
Data:

14:42:50.288 [parallel-1] DEBUG io.rsocket.FrameLogger - sending -> 
Frame => Stream ID: 0 Type: KEEPALIVE Flags: 0b10000000 Length: 14
Data:

14:42:51.283 [parallel-1] DEBUG io.rsocket.FrameLogger - sending -> 
Frame => Stream ID: 0 Type: KEEPALIVE Flags: 0b10000000 Length: 14
Data:

14:42:52.283 [parallel-1] DEBUG io.rsocket.FrameLogger - sending -> 
Frame => Stream ID: 0 Type: KEEPALIVE Flags: 0b10000000 Length: 14
Data:

io.rsocket.exceptions.ConnectionErrorException: No keep-alive acks for 6000 ms
	at io.rsocket.RSocketClient.terminate(RSocketClient.java:114)
	at io.rsocket.keepalive.KeepAliveSupport.tryTimeout(KeepAliveSupport.java:110)
	at io.rsocket.keepalive.KeepAliveSupport$ClientKeepAliveSupport.onIntervalTick(KeepAliveSupport.java:146)
	at io.rsocket.keepalive.KeepAliveSupport.lambda$start$0(KeepAliveSupport.java:54)
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:130)
	at reactor.core.publisher.FluxInterval$IntervalRunnable.run(FluxInterval.java:123)
	at reactor.core.scheduler.PeriodicWorkerTask.call(PeriodicWorkerTask.java:59)
	at reactor.core.scheduler.PeriodicWorkerTask.run(PeriodicWorkerTask.java:73)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
14:42:53.288 [reactor-tcp-nio-5] DEBUG reactor.netty.resources.PooledConnectionProvider - [id: 0x9a58b06f, L:/127.0.0.1:49439 ! R:localhost/127.0.0.1:8001] Channel cleaned, now 0 active connections and 1 inactive connections
```

**Comment by piotr-signalfx** [comment]
1.0.0-RC1, same issue

**Comment by piotr-signalfx** [comment]
For comparison 0.12.2-RC2:
```4:53:54.562 [reactor-tcp-nio-5] DEBUG reactor.netty.resources.PooledConnectionProvider - [id: 0xd85eccdd, L:/127.0.0.1:49496 - R:localhost/127.0.0.1:8001] Channel connected, now 1 active connections and 0 inactive connections
14:53:54.572 [main] DEBUG io.rsocket.FrameLogger - sending -> 
Frame => Stream ID: 1 Type: REQUEST_RESPONSE Flags: 0b100000000 Length: 13
Metadata:

Data:
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 50 49 4e 47                                     |PING            |
+--------+-------------------------------------------------+----------------+
14:53:54.572 [reactor-tcp-nio-5] DEBUG reactor.netty.channel.ChannelOperationsHandler - [id: 0xd85eccdd, L:/127.0.0.1:49496 - R:localhost/127.0.0.1:8001] Writing object CompositeByteBuf(ridx: 0, widx: 16, cap: 16, components=2)
14:53:54.574 [reactor-tcp-nio-6] DEBUG io.rsocket.FrameLogger - receiving -> 
Frame => Stream ID: 0 Type: SETUP Flags: 0b100000000 Length: 59
Metadata:

Data:

14:53:54.579 [reactor-tcp-nio-6] DEBUG io.rsocket.FrameLogger - receiving -> 
Frame => Stream ID: 1 Type: REQUEST_RESPONSE Flags: 0b100000000 Length: 13
Metadata:

Data:
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 50 49 4e 47                                     |PING            |
+--------+-------------------------------------------------+----------------+
14:53:54.582 [reactor-tcp-nio-6] DEBUG io.rsocket.FrameLogger - sending -> 
Frame => Stream ID: 1 Type: NEXT_COMPLETE Flags: 0b1100000 Length: 10
Data:
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 50 4f 4e 47                                     |PONG            |
+--------+-------------------------------------------------+----------------+
14:53:54.582 [reactor-tcp-nio-6] DEBUG reactor.netty.channel.ChannelOperationsHandler - [id: 0x58ae2694, L:/127.0.0.1:8001 - R:/127.0.0.1:49496] Writing object CompositeByteBuf(ridx: 0, widx: 13, cap: 13, components=2)
14:53:54.582 [reactor-tcp-nio-5] DEBUG io.rsocket.FrameLogger - receiving -> 
Frame => Stream ID: 1 Type: NEXT_COMPLETE Flags: 0b1100000 Length: 10
Data:
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 50 4f 4e 47                                     |PONG            |
+--------+-------------------------------------------------+----------------+
io.rsocket.util.ByteBufPayload@358ee631
```

**Comment by piotr-signalfx** [comment]
Here is my test case: https://github.com/piotr-signalfx/rsocket-test-case

**Comment by mostroverkhov** [comment]
@piotr-signalfx spring boot starter pulls in outdated `reactor-netty` dependencies: changing `2.1.3.RELEASE` to `2.1.6.RELEASE` should fix reproducer. Importing `reactor-netty` BOM of at least `Californium-SR8` should help also.

**Comment by piotr-signalfx** [comment]
Thank you for a prompt response. I can confirm that bumping spring-boot to 2.1.6.RELEASE resolves the issue. Thanks a lot for your help.
