### ISSUE TITLE
AssertionError occurred during closing rsocket

### ISSUE THREAD

**Issue by SerCeMan** [rsocket/rsocket-java#679]
Hi, RSocket team!

I noticed that some of my tests fail with this error periodically during clean-up. Unfortunately, I don't have a stable test case to reproduce this. As far as I'm aware, all of the interactions with rsocket are finished by the time I call `dispose()`. Do you have any advice on how I can debug this? 

```
java.lang.AssertionError: null is not a legitimate internal value. Concurrent Modification?
	at io.rsocket.internal.SynchronizedIntObjectHashMap.toExternal(SynchronizedIntObjectHashMap.java:99)
	at io.rsocket.internal.SynchronizedIntObjectHashMap.access$900(SynchronizedIntObjectHashMap.java:38)
	at io.rsocket.internal.SynchronizedIntObjectHashMap$PrimitiveIterator.value(SynchronizedIntObjectHashMap.java:664)
	at io.rsocket.internal.SynchronizedIntObjectHashMap$1$1.next(SynchronizedIntObjectHashMap.java:235)
	at java.base/java.lang.Iterable.forEach(Iterable.java:74)
	at io.rsocket.RSocketRequester.terminate(RSocketRequester.java:478)
	at io.rsocket.RSocketRequester.lambda$new$0(RSocketRequester.java:93)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.runFinally(FluxDoFinally.java:156)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:139)
	at reactor.core.publisher.MonoProcessor$NextInner.onComplete(MonoProcessor.java:592)
	at reactor.core.publisher.MonoProcessor.onNext(MonoProcessor.java:380)
	at reactor.core.publisher.MonoProcessor.onComplete(MonoProcessor.java:335)
	at io.rsocket.internal.BaseDuplexConnection.dispose(BaseDuplexConnection.java:23)
	at io.rsocket.internal.ClientServerInputMultiplexer$InternalDuplexConnection.dispose(ClientServerInputMultiplexer.java:205)
	at io.rsocket.RSocketRequester.dispose(RSocketRequester.java:188)
	at io.rsocket.util.RSocketProxy.dispose(RSocketProxy.java:65)
        ...
```

**Comment by OlegDokuka** [comment]
Seem to be a bug! Will take a look at that. Thanks for the reporting.
