### ISSUE TITLE
NPE in client if server is terminated

### ISSUE THREAD

**Issue by hban** [rsocket/rsocket-java#695]
I'm testing with echo example, modified to use TCP transport. Server is ran in one process, and client in another, continuously sending requests.

If I forcefully kill the server process, client will throw NPE.

```
java.lang.NullPointerException
	at io.rsocket.RSocketRequester.lambda$handleSendProcessorCancel$2(RSocketRequester.java:148)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.rsocket.RSocketRequester.handleSendProcessorCancel(RSocketRequester.java:145)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.runFinally(FluxDoFinally.java:156)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:139)
	at reactor.netty.channel.MonoSendMany$SendManyInner.operationComplete(MonoSendMany.java:243)
	at reactor.netty.channel.MonoSendMany$SendManyInner.operationComplete(MonoSendMany.java:92)
	<snip>
```

Nothing actually break (AFAICS), but this does feel like a bug to me.

I can create a simple project to reproduce this if needed.

**Comment by mostroverkhov** [comment]
closed by #706
