### ISSUE TITLE
CancellationException: Inbound has been canceled on channel-based communication

### ISSUE THREAD

**Issue by Cesarla** [rsocket/rsocket-java#960]
Hi,

After upgrading  from `rsocket-java:1.0.2` to `1.1.0` I am experiencing cancel-signals not being propagated, but instead being captured by the default onErrorDropped. 

Here is a stack-trace:
```java
Operator called default onErrorDropped
java.util.concurrent.CancellationException: Inbound has been canceled
	at io.rsocket.core.RequestChannelResponderSubscriber.tryTerminate(RequestChannelResponderSubscriber.java:357)
	at io.rsocket.core.RequestChannelResponderSubscriber.handleCancel(RequestChannelResponderSubscriber.java:345)
	at io.rsocket.core.RSocketResponder.handleFrame(RSocketResponder.java:217)
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160)
	at io.rsocket.core.ClientServerInputMultiplexer$InternalDuplexConnection.onNext(ClientServerInputMultiplexer.java:248)
	at io.rsocket.core.ClientServerInputMultiplexer.onNext(ClientServerInputMultiplexer.java:129)
	at io.rsocket.core.ClientServerInputMultiplexer.onNext(ClientServerInputMultiplexer.java:48)
	at io.rsocket.resume.ResumableDuplexConnection$FrameReceivingSubscriber.onNext(ResumableDuplexConnection.java:323)
	at io.rsocket.resume.ResumableDuplexConnection$FrameReceivingSubscriber.onNext(ResumableDuplexConnection.java:287)
	at io.rsocket.core.SetupHandlingDuplexConnection.onNext(SetupHandlingDuplexConnection.java:118)
	at io.rsocket.core.SetupHandlingDuplexConnection.onNext(SetupHandlingDuplexConnection.java:19)
	at com.XXXXX.eventstream.MdcContextLifter.onNext(MdcContextLifter.java:27)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
	at com.XXXXX.eventstream.MdcContextLifter.onNext(MdcContextLifter.java:27)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
	at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:256)
	at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:362)
	at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:383)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:94)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

I see that there was a [commit](https://github.com/rsocket/rsocket-java/commit/2e84405090e585e320e53873cac2b3d80c0c17fc) affecting the `RequestChannelResponderSubscriber`, but I am not sure if it relates to this issue.

## Steps to Reproduce

Cancel a channel-based communication and eventually you'll experience this problem. (Heads up, the error does not reproduce all the time)

## Your Environment

* RSocket version(s) used: 1.1.0
* Other relevant libraries versions (eg. `netty`, ...): reactor-core: 3.4.0
* Platform (eg. JVM version (`javar -version`) or Node version (`node --version`)): OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode
* OS and version (eg `uname -a`): Darwin XXXXXX 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64

**Comment by OlegDokuka** [comment]
Hi @Cesarla! 

Thank you for trying the new 1.1.0 version!

> I see that there was a commit affecting the RequestChannelResponderSubscriber, but I am not sure if it relates to this issue.

Yes, you are right, this commit should fix your bug, thus I would really appreciate if you can check if logs appear in 1.1.1-SNAPSHOT

Cheers,
Oleh

**Comment by Cesarla** [comment]
Hi @OlegDokuka, I have tried, but the `1.1.1-SNAPSHOT` is actually released under [1.1.1-SNAPSHOT-SNAPSHOT](https://oss.jfrog.org/artifactory/webapp/#/artifacts/browse/tree/General/oss-snapshot-local/io/rsocket/rsocket-bom/1.1.1-SNAPSHOT-SNAPSHOT) and I am not able to download it from 'https://oss.jfrog.org/oss-snapshot-local'.

**Comment by OlegDokuka** [comment]
@Cesarla fixed. Should be available under `1.1.1-SNAPSHOT` shortly (~15 mins)

**Comment by Cesarla** [comment]
I am still getting the same error with `1.1.1-SNAPSHOT`:
```
	at io.rsocket.core.RequestChannelResponderSubscriber.tryTerminate(RequestChannelResponderSubscriber.java:358)
	at io.rsocket.core.RequestChannelResponderSubscriber.handleCancel(RequestChannelResponderSubscriber.java:346)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.rsocket.core.RSocketResponder.cleanUpSendingSubscriptions(RSocketResponder.java:186)
	at io.rsocket.core.RSocketResponder.doOnDispose(RSocketResponder.java:174)
	at io.rsocket.core.RSocketResponder.tryTerminate(RSocketResponder.java:108)
	at io.rsocket.core.RSocketResponder.tryTerminateOnConnectionClose(RSocketResponder.java:101)
	at reactor.core.publisher.LambdaMonoSubscriber.onComplete(LambdaMonoSubscriber.java:135)
	at reactor.core.publisher.NextProcessor$NextInner.onComplete(NextProcessor.java:400)
	at reactor.core.publisher.NextProcessor.tryEmitValue(NextProcessor.java:184)
	at reactor.core.publisher.NextProcessor.tryEmitEmpty(NextProcessor.java:136)
	at reactor.core.publisher.NextProcessor.onComplete(NextProcessor.java:131)
	at io.rsocket.resume.ResumableDuplexConnection.dispose(ResumableDuplexConnection.java:213)
	at io.rsocket.resume.ServerRSocketSession.dispose(ServerRSocketSession.java:231)
	at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4772)
	at io.rsocket.resume.SessionManager.dispose(SessionManager.java:68)
	at io.rsocket.core.ServerSetup$ResumableServerSetup.dispose(ServerSetup.java:147)
	at io.rsocket.core.RSocketServer$2.lambda$null$1(RSocketServer.java:297)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.runFinally(FluxDoFinally.java:163)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:146)
	at reactor.netty.FutureMono$FutureSubscription.operationComplete(FutureMono.java:180)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1163)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:761)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:737)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:608)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.close(DefaultChannelPipeline.java:1352)
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:622)
	at io.netty.channel.AbstractChannelHandlerContext.access$1200(AbstractChannelHandlerContext.java:61)
	at io.netty.channel.AbstractChannelHandlerContext$11.run(AbstractChannelHandlerContext.java:611)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by OlegDokuka** [comment]
@Cesarla In general that is an expected dropped error unless you have a specific use-case in which this should not happen. Can you please clarify how this one can be reproduced?

**Comment by Cesarla** [comment]
Hi @OlegDokuka, as you pointed out the issue was unrelated, I was able to migrate to 1.1.0 without problem, 
so closing the ticket.

Thanks

**Comment by derTobsch** [comment]
@Cesarla I am running in the same error. Can you give me a hint how you handled this?

**Comment by OlegDokuka** [comment]
@derTobsch it is not an error. It is just a log message saying that an exception proactively trying to terminate downstream was dropped. This will be improved in 1.1.1

**Comment by derTobsch** [comment]
Thanks for your response @OlegDokuka. is it ok to post on this closed issue? Otherwise I would open a new one.
My case is that we use `rsocket-js` in the frontend and `rsocket-java` in the backend and we want to know if someone closes the browser tab or closes the browser. So I am looking why we do not get any information in `doOnTerminate|Cancel|Error` but this information. Do you have a hint for me how we get the information that someone closed a tab/browser?
Our Stack is Spring Boot/Webflux/Rsocket in 2.4.3, so rsocket-java 1.1.0 and rsocket-js 0.0.23.

**Comment by OlegDokuka** [comment]
I guess what you would like is tracking the connection rather than the fact that logical stream was terminated.

What you need is to hook on `RSocket#onClose()` method which will signal the subscriber when the connection is closed

**Comment by derTobsch** [comment]
> I guess what you would like is tracking the connection rather than the fact that a logical stream was terminated.

Thanks for that input! Of course we want to track the connection and handle the close event.

> What you need is to hook on `RSocket#onClose()` method which will signal the subscriber when the connection is closed

Are there any examples? I am a little bit lost here right now. Should I add a new `@ConnectionMapping` with a "alive ping" so I can inject the `RSocketRequester` to get the rsocket? Or can I just inject a `RSocket` bean and add a hook on the onClose()?

**Comment by derTobsch** [comment]
k, I was just on the wrong path. Did it in the frontend. Thanks for your response and time.

**Comment by OlegDokuka** [comment]
@derTobsch if we talk about spring, you should do the following 


```
@ConnectionMapping
void handleConnection(RSocketRequester requester) {
	requester.rsocket().onClose().doFinally(terminalSignal -> {
	 // write the logic to handling client disconnection
	})
	.subscribe();
}
```

**Comment by derTobsch** [comment]
> @derTobsch if we talk about spring, you should do the following
> 
> ```
> @ConnectionMapping
> void handleConnection(RSocketRequester requester) {
> 	requester.rsocket().onClose().doFinally(terminalSignal -> {
> 	 // write the logic to handling client disconnection
> 	})
> 	.subscribe();
> }
> ```

Thanks! I already did that, but the think is that I need more information and not only the `terminalSignal`. So with your input and a fresh coffee I thought this is not what I wanted and so I listen to the `onbeforeunload` in js and send the correct message.

**Comment by joshiste** [comment]
> This will be improved in 1.1.1

the due date has now passed by for 9 days. What is the current ETA for that release?
